---
title: "EDA Template"
author: "Waylon"
date: "2017/9/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## 读取数据

## 检查缺失值

## 基本统计信息

## 单一变量分析
### 连续型变量

#### 了解变量分布情况
```{r }
# 直方图

# 散点图

# 水平箱线图
geom_boxplot() + coord_flip()

## qq图
```

#### 数据分布模式

+ 双峰、长尾、

### 类别型变量

#### 了解变量分布情况
```{r}
# 条形图


```

#### 数据分布模式
+ 常见值、异常值、集群


### 异常值处理
+ 检测异常值

+处理：删除观测、替换为`NA`

## 多变量分析

### 类别型变量对连续型变量的相互作用

```{r }
# 频率图
geom_freqpoly( y = ..density..)

# 箱线图
ggplot(data = diamonds, mapping = aes(x = cut, y = price)) +
  geom_boxplot()
```

### 两个类别型变量的相互作用

```{r }
# 处理观测数图
ggplot(data = diamonds) +
  geom_count(mapping = aes(x = cut, y = color))

# 马赛克图
diamonds %>% 
  count(color, cut) %>%  
  ggplot(mapping = aes(x = color, y = cut)) +
    geom_tile(mapping = aes(fill = n))
```

### 两个连续型变量的关系
```{r }
# 散点图
ggplot(data = diamonds) + 
  geom_point(mapping = aes(x = carat, y = price), alpha = 1 / 100)

# 方块图或六边形图
smaller <- diamonds %>% 
  filter(carat < 3)

# 方块图
ggplot(data = smaller) +
  geom_bin2d(mapping = aes(x = carat, y = price))

# install.packages("hexbin")

# 六边形图
ggplot(data = smaller) +
  geom_hex(mapping = aes(x = carat, y = price))

# 箱线图
ggplot(data = smaller, mapping = aes(x = carat, y = price)) + 
  geom_boxplot(mapping = aes(group = cut_width(carat, 0.1)))
```

## 数据的模式
+ 模式是否由巧合导致
+ 如何描述模式隐含的关系
+ 这种关系有多强的影响
+ 还有哪些变量会影响这种关系
+ 在数据集的子集中关系是否仍存在
+ 如果两个变量相关，可以使用一个变量来更好地预测另一个变量。如果这种相关是由于因果关系导致的，可以使用一个变量来控制另一个变量。

